import React from 'react';
import usePickupTracking from '../../hooks/usePickupTracking';

const steps = ['ASSIGNED', 'PICKUP', 'IN_TRANSIT', 'DELIVERED'];
function label(value) { return value.replace('_', ' '); }
function proofLink(url, title) { return url ? <a className="proof-gallery-item" href={url} target="_blank" rel="noreferrer"><span>{title}</span><strong>Open proof ↗</strong></a> : <div className="proof-gallery-item is-empty"><span>{title}</span><strong>Not recorded</strong></div>; }

export default function PickupTrackingView({ pickupId, user, role, onBack }) {
  const { pickup, loading, error } = usePickupTracking(pickupId, user?.id, role);
  if (loading) return <main className="tracking-shell"><div className="dispatch-empty">Loading pickup tracking...</div></main>;
  if (error || !pickup) return <main className="tracking-shell"><div className="driver-error">{error || 'Pickup not found.'}</div></main>;
  const currentIndex = steps.indexOf(pickup.status);
  return <main className="tracking-shell"><button className="tracking-back-button" onClick={onBack}>← Back to workspace</button><header className="tracking-heading"><div><span className={`dispatch-status dispatch-status-${pickup.status.toLowerCase()}`}>{label(pickup.status)}</span><h1>{pickup.donations?.food_name || 'Surplus pickup'}</h1><p>{pickup.shelters?.organization_name || 'Shelter delivery'} · {pickup.donations?.quantity || '—'} {pickup.donations?.unit || 'units'}</p></div></header><section className="tracking-timeline">{steps.map((step, index) => <div className={index <= currentIndex ? 'is-reached' : ''} key={step}><span>{index + 1}</span><strong>{label(step)}</strong><small>{step === 'PICKUP' ? pickup.picked_up_at || 'Pending' : step === 'DELIVERED' ? pickup.delivered_at || 'Pending' : step === 'ASSIGNED' ? pickup.assigned_at || 'Pending' : pickup.updated_at || 'Pending'}</small></div>)}</section><div className="tracking-grid"><section className="tracking-card"><span className="section-eyebrow">DRIVER</span><h2>{pickup.drivers?.name || 'Driver not assigned'}</h2><p>{pickup.drivers?.phone || 'Contact details unavailable'} · {pickup.drivers?.vehicle_type || 'Vehicle pending'}</p>{pickup.status === 'IN_TRANSIT' && pickup.drivers?.current_lat ? <div className="tracking-location">Live location · {pickup.drivers.current_lat.toFixed(4)}, {pickup.drivers.current_lng.toFixed(4)}</div> : null}<div className="tracking-route"><span>{pickup.donations?.pickup_address || 'Pickup address pending'}</span><strong>→</strong><span>{pickup.shelters?.address || 'Delivery address pending'}</span></div></section><section className="tracking-card"><span className="section-eyebrow">PROOF GALLERY</span><div className="proof-gallery">{proofLink(pickup.proof_photo_url, 'Pickup photo')}{proofLink(pickup.proof_signature_url, 'Pickup signature')}{proofLink(pickup.delivery_proof_photo_url, 'Delivery photo')}{proofLink(pickup.delivery_proof_signature_url, 'Shelter signature')}</div>{pickup.temperature_c !== null && pickup.temperature_c !== undefined ? <div className="temperature-log">Recorded temperature: <strong>{pickup.temperature_c} °C</strong></div> : null}</section></div></main>;
}